### ISSUE TITLE
Suggestions for hellohook cog 

### ISSUE THREAD

**Issue by Rhett-7** [coffeebank/coffee-cogs#10]
`hellohook` please support the following [variables]( https://discordpy.readthedocs.io/en/stable/api.html?highlight=guild#discord.Guild.member_count) (`print(abs(int(744)) % 10) # 4`)
`https://&&SERVERCOUNT&&` - Number of members
`https://&&ORDSERVERCOUNT&&` - Number of members but with `th`, `rd`, `nd`

Also have the ability to set a [leave](https://discordpy.readthedocs.io/en/stable/api.html?highlight=on_member_remove#discord.on_member_remove) webhook and a join webhook to be able to support the following
![image](https://user-images.githubusercontent.com/76634333/166611972-f2917420-7496-43cc-b70e-43206bcbf19d.png)

**Comment by coffeebank** [comment]
Leave webhooks will be a larger project that may take more time separately

**Comment by coffeebank** [comment]
Latest update adds servercount variables :)
