### ISSUE TITLE
emotes: Use async library instead of requests

### ISSUE THREAD

**Issue by MouseMoosz** [coffeebank/coffee-cogs#15]
Use Async Library (like [`aiohttp`](https://docs.aiohttp.org/en/stable/)) instead of `requests` in `emotes` cog.

**Comment by coffeebank** [comment]
Sending as personal note
Can test the PR sometime soon

import asyncio
import aiohttp
https://docs.aiohttp.org/en/stable/client_quickstart.html#json-response-content

**Comment by coffeebank** [comment]
Thanks for your contribution, should be live now :)
