### ISSUE TITLE
msgmover: Migrate to support Red 3.5

### ISSUE THREAD

**Issue by bscabl** [coffeebank/coffee-cogs#23]
Red updated to 3.5 .. all cogs started saying they needed python 3.11 - updated python.. most working now.. but msgmover wont even load.

**Comment by coffeebank** [comment]
Red 3.5 was a large update. I am working on upgrading coffee-cogs to be compatible, but it may take a while and there is no ETA. Large parts will need to be rewritten. Feel free to [join the Discord](https://coffeebank.github.io/discord) and stay tuned on the progress.... Thanks for your patience :')

**Comment by bscabl** [comment]
thanks for the rapid reply.. ill join the discord.. loooove this cog

**Comment by coffeebank** [comment]
Should be good now - feel free to give msgmover a try and let me know if there are any bugs/outstanding issues! :)

**Comment by bscabl** [comment]
can confirm functionality has resumed. impressive turnaround! thanks!
