### ISSUE TITLE
coffeetools: `choose` can be abused to spam links and mentions

### ISSUE THREAD

**Issue by coffeebank** [coffeebank/coffee-cogs#5]
Because the text is just returned, this can be abused to elevate privileges and send links with nasty link previews, abuse @/everyone pings, among many other potential violations.

```
async def choose(self, ctx, *, choosetext):
    choosearray = choosetext.split("|")
    return await ctx.send(random.choice(choosearray))
```

**Comment by caupcakes** [comment]
among? among us?
